tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "awscli"
brew "sqlite"
brew "python"
brew "crystal-lang"
brew "curl", args: ["with-openssl"]
brew "elixir"
brew "emacs", args: ["with-cocoa"]
brew "fish"
brew "git"
brew "go"
brew "heroku"
brew "httpie"
brew "hyper"
brew "postgresql", restart_service: true
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "the_silver_searcher"
brew "tmux"
brew "wget"
brew "wrk"
brew "yarn"
brew "zsh"
brew "zsh-completions"
cask "firefox"
cask "hyper"

