tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"

brew "awscli"
brew "sqlite"
brew "python"
brew "crystal-lang"
brew "curl", args: ["with-openssl"]
brew "elixir"
brew "emacs", args: ["with-cocoa", "with-gnutls"]
brew "fish"
brew "git"
brew "go"
brew "heroku"
brew "httpie"
brew "hyper"
brew "mas"
brew "node"
brew "postgresql", restart_service: true
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "the_silver_searcher"
brew "tmux"
brew "wget"
brew "wrk"
brew "yarn"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "appcleaner"
cask "dash"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "hyper"
cask "omnifocus"
cask "parallels-desktop"
cask "spotify"
cask "sublime-text"
cask "visual-studio-code"
